name: Frontend Build Check
run-name: ${{ github.actor }} Build Check

on:
  pull_request:
    branches:
      - main  
    paths:
      - 'aquawatch_mobile_app/**'
  workflow_dispatch: # Manual trigger
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: ./aquawatch_mobile_app
        run: npm install

      - name: Expo Doctor Check
        working-directory: './aquawatch_mobile_app'
        run: |
          npx expo-doctor || echo "Expo Doctor found issues, but continuing..."

      - name: Lint Check              
        working-directory: './aquawatch_mobile_app'
        run: |
          npx expo lint || echo "Linting found issues, but continuing..."

      - name: npm Audit 
        working-directory: './aquawatch_mobile_app'
        run: |
          npm audit --audit-level=low || echo "npm audit found vulnerabilities, but continuing..."
